package com.myos.entity;

import jakarta.persistence.*;
import lombok.*;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * @Entity tells Spring Data JPA that this class is a JPA entity that maps directly
 * to a table in PostgreSQL named "ai_model_configs".
 *
 * @Table defines specific database table metadata. Here we explicitly map to the
 * table created in migration V14.
 *
 * Lombok Annotations:
 * - @Getter / @Setter: Automatically generates boilerplate getter/setter methods.
 * - @Builder: Implements the Builder design pattern, allowing clean instance creation (e.g. AiModelConfig.builder().provider(...).build()).
 * - @NoArgsConstructor: Generates a public default constructor required by JPA Hibernate.
 * - @AllArgsConstructor: Generates an all-arguments constructor required by Lombok's @Builder.
 */
@Entity
@Table(name = "ai_model_configs")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AiModelConfig {

    /**
     * @Id designates this field as the primary key.
     * @GeneratedValue specifies UUID generation. Spring uses Java's native generator
     * to populate it before persists.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    // The provider name (OLLAMA, OPENAI, ANTHROPIC)
    @Column(nullable = false)
    private String provider;

    // The targeted LLM model (e.g. llama3, gpt-4o, claude-3-5-sonnet)
    @Column(name = "model_name", nullable = false)
    private String modelName;

    // The server API endpoint (for local setups like Ollama)
    @Column(name = "base_url")
    private String baseUrl;

    // Symmetric AES-256-GCM encrypted API key.
    // Stored as a VARCHAR up to 512 bytes to handle GCM tags and Base64 wrapping.
    @Column(name = "api_key", length = 512)
    private String apiKey;

    // Active status. Identifies which config is currently active.
    // Maps to idx_only_one_active_model index to protect data invariants.
    @Column(name = "is_active", nullable = false)
    private boolean isActive;

    /**
     * Audit fields.
     * insertable = false, updatable = false prevents JPA from overwriting values
     * generated by PostgreSQL default constraints.
     */
    @Column(name = "created_at", insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", insertable = false, updatable = false)
    private OffsetDateTime updatedAt;
}
